name: 4DCT
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pandas
  - xarray
  - pytorch::pytorch-cuda=11.8
  - torchvision
  - matplotlib
  - seaborn
  - notebook
  - ipykernel
  - ipywidgets
  - tqdm
  - parse
  - hvplot
  - nibabel
  - fenics
  - vedo
  - requests>=2.31
  - pip
  - pip:
    - TotalSegmentator

